package de.uni_muenster.sopra2015.gruppe8.octobus.model;

/**
 * Used to store the data of a stopping point.
 */
public class StoppingPoint
{

    private int id;
    private String name;

	public StoppingPoint()
	{

	}

    @Override
    /**
     * This is needed for "removeAll" to work in "ControllerFormBusStop".
     * Originally generated by IntelliJ IDEA, but checked by hand and modified.
     */
    public boolean equals(Object o)
    {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        StoppingPoint that = (StoppingPoint) o;

        if (id != that.id) return false;

        return true;
    }

    @Override
    /**
     * Generated by IntelliJ IDEA, checked by hand.
     */
    public int hashCode()
    {
        int result = id;
        result = 31 * result + name.hashCode();
        return result;
    }

    public StoppingPoint(int id, String name)
    {
        this.id = id;
        this.name = name;
    }

    public int getId()
    {
        return id;
    }

    public String getName()
    {
        return name;
    }

    public void setId(int id)
    {
        this.id = id;
    }

    public void setName(String name)
    {
        this.name = name;
    }
}
