/**
 * This class is generated by jOOQ
 */
package de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated;

/**
 * Convenience access to all tables in 
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table Haltestellenkombis
	 */
	public static final de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Haltestellenkombis HALTESTELLENKOMBIS = de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Haltestellenkombis.HALTESTELLENKOMBIS;

	/**
	 * The table Linien mit Haltestellen inkl. Haltepunkten
	 */
	public static final de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Linien_mit_haltestellen_inkl_2e_haltepunkten LINIEN_MIT_HALTESTELLEN_INKL_2e_HALTEPUNKTEN = de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Linien_mit_haltestellen_inkl_2e_haltepunkten.LINIEN_MIT_HALTESTELLEN_INKL_2e_HALTEPUNKTEN;

	/**
	 * The table Linien mit ihren Abfahrten
	 */
	public static final de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Linien_mit_ihren_abfahrten LINIEN_MIT_IHREN_ABFAHRTEN = de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Linien_mit_ihren_abfahrten.LINIEN_MIT_IHREN_ABFAHRTEN;

	/**
	 * The table busStops
	 */
	public static final de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Busstops BUSSTOPS = de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Busstops.BUSSTOPS;

	/**
	 * The table busStops_stoppingPoints
	 */
	public static final de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.BusstopsStoppingpoints BUSSTOPS_STOPPINGPOINTS = de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.BusstopsStoppingpoints.BUSSTOPS_STOPPINGPOINTS;

	/**
	 * The table buses
	 */
	public static final de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Buses BUSES = de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Buses.BUSES;

	/**
	 * The table employees
	 */
	public static final de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees EMPLOYEES = de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES;

	/**
	 * The table routes
	 */
	public static final de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Routes ROUTES = de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Routes.ROUTES;

	/**
	 * The table routes_startTimes
	 */
	public static final de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.RoutesStarttimes ROUTES_STARTTIMES = de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.RoutesStarttimes.ROUTES_STARTTIMES;

	/**
	 * The table routes_stops
	 */
	public static final de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.RoutesStops ROUTES_STOPS = de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.RoutesStops.ROUTES_STOPS;

	/**
	 * The table soldTickets
	 */
	public static final de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Soldtickets SOLDTICKETS = de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Soldtickets.SOLDTICKETS;

	/**
	 * The table sqlite_sequence
	 */
	public static final de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.SqliteSequence SQLITE_SEQUENCE = de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.SqliteSequence.SQLITE_SEQUENCE;

	/**
	 * The table tickets
	 */
	public static final de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Tickets TICKETS = de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Tickets.TICKETS;

	/**
	 * The table tours
	 */
	public static final de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Tours TOURS = de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Tours.TOURS;
}
