/**
 * This class is generated by jOOQ
 */
package de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BusesRecord extends org.jooq.impl.UpdatableRecordImpl<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.BusesRecord> implements org.jooq.Record8<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Boolean> {

	private static final long serialVersionUID = -1312589597;

	/**
	 * Setter for <code>buses.buses_id</code>.
	 */
	public void setBusesId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>buses.buses_id</code>.
	 */
	public java.lang.Integer getBusesId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>buses.licencePlate</code>.
	 */
	public void setLicenceplate(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>buses.licencePlate</code>.
	 */
	public java.lang.String getLicenceplate() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>buses.numberOfSeats</code>.
	 */
	public void setNumberofseats(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>buses.numberOfSeats</code>.
	 */
	public java.lang.Integer getNumberofseats() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>buses.standingRoom</code>.
	 */
	public void setStandingroom(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>buses.standingRoom</code>.
	 */
	public java.lang.Integer getStandingroom() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>buses.manufacturer</code>.
	 */
	public void setManufacturer(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>buses.manufacturer</code>.
	 */
	public java.lang.String getManufacturer() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>buses.model</code>.
	 */
	public void setModel(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>buses.model</code>.
	 */
	public java.lang.String getModel() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>buses.nextInspectionDue</code>.
	 */
	public void setNextinspectiondue(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>buses.nextInspectionDue</code>.
	 */
	public java.lang.Integer getNextinspectiondue() {
		return (java.lang.Integer) getValue(6);
	}

	/**
	 * Setter for <code>buses.articulatedBus</code>.
	 */
	public void setArticulatedbus(java.lang.Boolean value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>buses.articulatedBus</code>.
	 */
	public java.lang.Boolean getArticulatedbus() {
		return (java.lang.Boolean) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Boolean> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Boolean> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Buses.BUSES.BUSES_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Buses.BUSES.LICENCEPLATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Buses.BUSES.NUMBEROFSEATS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Buses.BUSES.STANDINGROOM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Buses.BUSES.MANUFACTURER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Buses.BUSES.MODEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Buses.BUSES.NEXTINSPECTIONDUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field8() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Buses.BUSES.ARTICULATEDBUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getBusesId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getLicenceplate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getNumberofseats();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getStandingroom();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getManufacturer();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getModel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getNextinspectiondue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value8() {
		return getArticulatedbus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BusesRecord value1(java.lang.Integer value) {
		setBusesId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BusesRecord value2(java.lang.String value) {
		setLicenceplate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BusesRecord value3(java.lang.Integer value) {
		setNumberofseats(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BusesRecord value4(java.lang.Integer value) {
		setStandingroom(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BusesRecord value5(java.lang.String value) {
		setManufacturer(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BusesRecord value6(java.lang.String value) {
		setModel(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BusesRecord value7(java.lang.Integer value) {
		setNextinspectiondue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BusesRecord value8(java.lang.Boolean value) {
		setArticulatedbus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BusesRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.Integer value3, java.lang.Integer value4, java.lang.String value5, java.lang.String value6, java.lang.Integer value7, java.lang.Boolean value8) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached BusesRecord
	 */
	public BusesRecord() {
		super(de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Buses.BUSES);
	}

	/**
	 * Create a detached, initialised BusesRecord
	 */
	public BusesRecord(java.lang.Integer busesId, java.lang.String licenceplate, java.lang.Integer numberofseats, java.lang.Integer standingroom, java.lang.String manufacturer, java.lang.String model, java.lang.Integer nextinspectiondue, java.lang.Boolean articulatedbus) {
		super(de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Buses.BUSES);

		setValue(0, busesId);
		setValue(1, licenceplate);
		setValue(2, numberofseats);
		setValue(3, standingroom);
		setValue(4, manufacturer);
		setValue(5, model);
		setValue(6, nextinspectiondue);
		setValue(7, articulatedbus);
	}
}
