/**
 * This class is generated by jOOQ
 */
package de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BusesRecord extends org.jooq.impl.UpdatableRecordImpl<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.BusesRecord> implements org.jooq.Record7<java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Object, java.lang.Object, java.lang.Integer, java.lang.Boolean> {

	private static final long serialVersionUID = -1167373392;

	/**
	 * Setter for <code>buses.licencePlate</code>.
	 */
	public void setLicenceplate(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>buses.licencePlate</code>.
	 */
	public java.lang.String getLicenceplate() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>buses.numberOfSeats</code>.
	 */
	public void setNumberofseats(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>buses.numberOfSeats</code>.
	 */
	public java.lang.Integer getNumberofseats() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>buses.standingRoom</code>.
	 */
	public void setStandingroom(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>buses.standingRoom</code>.
	 */
	public java.lang.Integer getStandingroom() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>buses.manufacturer</code>.
	 */
	public void setManufacturer(java.lang.Object value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>buses.manufacturer</code>.
	 */
	public java.lang.Object getManufacturer() {
		return (java.lang.Object) getValue(3);
	}

	/**
	 * Setter for <code>buses.model</code>.
	 */
	public void setModel(java.lang.Object value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>buses.model</code>.
	 */
	public java.lang.Object getModel() {
		return (java.lang.Object) getValue(4);
	}

	/**
	 * Setter for <code>buses.nextInspectionDateDue</code>.
	 */
	public void setNextinspectiondatedue(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>buses.nextInspectionDateDue</code>.
	 */
	public java.lang.Integer getNextinspectiondatedue() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>buses.articulatedBus</code>.
	 */
	public void setArticulatedbus(java.lang.Boolean value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>buses.articulatedBus</code>.
	 */
	public java.lang.Boolean getArticulatedbus() {
		return (java.lang.Boolean) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Object, java.lang.Object, java.lang.Integer, java.lang.Boolean> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Object, java.lang.Object, java.lang.Integer, java.lang.Boolean> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Buses.BUSES.LICENCEPLATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Buses.BUSES.NUMBEROFSEATS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Buses.BUSES.STANDINGROOM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Object> field4() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Buses.BUSES.MANUFACTURER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Object> field5() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Buses.BUSES.MODEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Buses.BUSES.NEXTINSPECTIONDATEDUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field7() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Buses.BUSES.ARTICULATEDBUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getLicenceplate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getNumberofseats();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getStandingroom();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Object value4() {
		return getManufacturer();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Object value5() {
		return getModel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getNextinspectiondatedue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value7() {
		return getArticulatedbus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BusesRecord value1(java.lang.String value) {
		setLicenceplate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BusesRecord value2(java.lang.Integer value) {
		setNumberofseats(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BusesRecord value3(java.lang.Integer value) {
		setStandingroom(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BusesRecord value4(java.lang.Object value) {
		setManufacturer(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BusesRecord value5(java.lang.Object value) {
		setModel(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BusesRecord value6(java.lang.Integer value) {
		setNextinspectiondatedue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BusesRecord value7(java.lang.Boolean value) {
		setArticulatedbus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BusesRecord values(java.lang.String value1, java.lang.Integer value2, java.lang.Integer value3, java.lang.Object value4, java.lang.Object value5, java.lang.Integer value6, java.lang.Boolean value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached BusesRecord
	 */
	public BusesRecord() {
		super(de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Buses.BUSES);
	}

	/**
	 * Create a detached, initialised BusesRecord
	 */
	public BusesRecord(java.lang.String licenceplate, java.lang.Integer numberofseats, java.lang.Integer standingroom, java.lang.Object manufacturer, java.lang.Object model, java.lang.Integer nextinspectiondatedue, java.lang.Boolean articulatedbus) {
		super(de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Buses.BUSES);

		setValue(0, licenceplate);
		setValue(1, numberofseats);
		setValue(2, standingroom);
		setValue(3, manufacturer);
		setValue(4, model);
		setValue(5, nextinspectiondatedue);
		setValue(6, articulatedbus);
	}
}
