/**
 * This class is generated by jOOQ
 */
package de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BusstopsStoppingpointsRecord extends org.jooq.impl.UpdatableRecordImpl<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.BusstopsStoppingpointsRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.Integer, java.lang.String> {

	private static final long serialVersionUID = -1151301342;

	/**
	 * Setter for <code>busStops_stoppingPoints.busStops_stoppingPoints_id</code>.
	 */
	public void setBusstopsStoppingpointsId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>busStops_stoppingPoints.busStops_stoppingPoints_id</code>.
	 */
	public java.lang.Integer getBusstopsStoppingpointsId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>busStops_stoppingPoints.busStops_id</code>.
	 */
	public void setBusstopsId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>busStops_stoppingPoints.busStops_id</code>.
	 */
	public java.lang.Integer getBusstopsId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>busStops_stoppingPoints.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>busStops_stoppingPoints.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.BusstopsStoppingpoints.BUSSTOPS_STOPPINGPOINTS.BUSSTOPS_STOPPINGPOINTS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.BusstopsStoppingpoints.BUSSTOPS_STOPPINGPOINTS.BUSSTOPS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.BusstopsStoppingpoints.BUSSTOPS_STOPPINGPOINTS.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getBusstopsStoppingpointsId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getBusstopsId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BusstopsStoppingpointsRecord value1(java.lang.Integer value) {
		setBusstopsStoppingpointsId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BusstopsStoppingpointsRecord value2(java.lang.Integer value) {
		setBusstopsId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BusstopsStoppingpointsRecord value3(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BusstopsStoppingpointsRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.String value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached BusstopsStoppingpointsRecord
	 */
	public BusstopsStoppingpointsRecord() {
		super(de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.BusstopsStoppingpoints.BUSSTOPS_STOPPINGPOINTS);
	}

	/**
	 * Create a detached, initialised BusstopsStoppingpointsRecord
	 */
	public BusstopsStoppingpointsRecord(java.lang.Integer busstopsStoppingpointsId, java.lang.Integer busstopsId, java.lang.String name) {
		super(de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.BusstopsStoppingpoints.BUSSTOPS_STOPPINGPOINTS);

		setValue(0, busstopsStoppingpointsId);
		setValue(1, busstopsId);
		setValue(2, name);
	}
}
