/**
 * This class is generated by jOOQ
 */
package de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BusstopsStoppingpointsRecord extends org.jooq.impl.UpdatableRecordImpl<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.BusstopsStoppingpointsRecord> implements org.jooq.Record5<java.lang.Integer, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object> {

	private static final long serialVersionUID = 1904599157;

	/**
	 * Setter for <code>busStops_stoppingPoints.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>busStops_stoppingPoints.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>busStops_stoppingPoints.busStops_name</code>.
	 */
	public void setBusstopsName(java.lang.Object value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>busStops_stoppingPoints.busStops_name</code>.
	 */
	public java.lang.Object getBusstopsName() {
		return (java.lang.Object) getValue(1);
	}

	/**
	 * Setter for <code>busStops_stoppingPoints.busStops_locationX</code>.
	 */
	public void setBusstopsLocationx(java.lang.Object value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>busStops_stoppingPoints.busStops_locationX</code>.
	 */
	public java.lang.Object getBusstopsLocationx() {
		return (java.lang.Object) getValue(2);
	}

	/**
	 * Setter for <code>busStops_stoppingPoints.busStops_locationY</code>.
	 */
	public void setBusstopsLocationy(java.lang.Object value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>busStops_stoppingPoints.busStops_locationY</code>.
	 */
	public java.lang.Object getBusstopsLocationy() {
		return (java.lang.Object) getValue(3);
	}

	/**
	 * Setter for <code>busStops_stoppingPoints.name</code>.
	 */
	public void setName(java.lang.Object value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>busStops_stoppingPoints.name</code>.
	 */
	public java.lang.Object getName() {
		return (java.lang.Object) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.BusstopsStoppingpoints.BUSSTOPS_STOPPINGPOINTS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Object> field2() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.BusstopsStoppingpoints.BUSSTOPS_STOPPINGPOINTS.BUSSTOPS_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Object> field3() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.BusstopsStoppingpoints.BUSSTOPS_STOPPINGPOINTS.BUSSTOPS_LOCATIONX;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Object> field4() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.BusstopsStoppingpoints.BUSSTOPS_STOPPINGPOINTS.BUSSTOPS_LOCATIONY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Object> field5() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.BusstopsStoppingpoints.BUSSTOPS_STOPPINGPOINTS.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Object value2() {
		return getBusstopsName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Object value3() {
		return getBusstopsLocationx();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Object value4() {
		return getBusstopsLocationy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Object value5() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BusstopsStoppingpointsRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BusstopsStoppingpointsRecord value2(java.lang.Object value) {
		setBusstopsName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BusstopsStoppingpointsRecord value3(java.lang.Object value) {
		setBusstopsLocationx(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BusstopsStoppingpointsRecord value4(java.lang.Object value) {
		setBusstopsLocationy(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BusstopsStoppingpointsRecord value5(java.lang.Object value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BusstopsStoppingpointsRecord values(java.lang.Integer value1, java.lang.Object value2, java.lang.Object value3, java.lang.Object value4, java.lang.Object value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached BusstopsStoppingpointsRecord
	 */
	public BusstopsStoppingpointsRecord() {
		super(de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.BusstopsStoppingpoints.BUSSTOPS_STOPPINGPOINTS);
	}

	/**
	 * Create a detached, initialised BusstopsStoppingpointsRecord
	 */
	public BusstopsStoppingpointsRecord(java.lang.Integer id, java.lang.Object busstopsName, java.lang.Object busstopsLocationx, java.lang.Object busstopsLocationy, java.lang.Object name) {
		super(de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.BusstopsStoppingpoints.BUSSTOPS_STOPPINGPOINTS);

		setValue(0, id);
		setValue(1, busstopsName);
		setValue(2, busstopsLocationx);
		setValue(3, busstopsLocationy);
		setValue(4, name);
	}
}
