/**
 * This class is generated by jOOQ
 */
package de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmployeesRecord extends org.jooq.impl.UpdatableRecordImpl<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.EmployeesRecord> implements org.jooq.Record18<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.Boolean, java.lang.Boolean, java.lang.Boolean, java.lang.Boolean> {

	private static final long serialVersionUID = 1335475450;

	/**
	 * Setter for <code>employees.employees_id</code>.
	 */
	public void setEmployeesId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>employees.employees_id</code>.
	 */
	public java.lang.Integer getEmployeesId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>employees.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>employees.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>employees.firstName</code>.
	 */
	public void setFirstname(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>employees.firstName</code>.
	 */
	public java.lang.String getFirstname() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>employees.address</code>.
	 */
	public void setAddress(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>employees.address</code>.
	 */
	public java.lang.String getAddress() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>employees.zipCode</code>.
	 */
	public void setZipcode(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>employees.zipCode</code>.
	 */
	public java.lang.String getZipcode() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>employees.city</code>.
	 */
	public void setCity(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>employees.city</code>.
	 */
	public java.lang.String getCity() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>employees.dateOfBirth</code>.
	 */
	public void setDateofbirth(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>employees.dateOfBirth</code>.
	 */
	public java.lang.Integer getDateofbirth() {
		return (java.lang.Integer) getValue(6);
	}

	/**
	 * Setter for <code>employees.phone</code>.
	 */
	public void setPhone(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>employees.phone</code>.
	 */
	public java.lang.String getPhone() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>employees.email</code>.
	 */
	public void setEmail(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>employees.email</code>.
	 */
	public java.lang.String getEmail() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>employees.username</code>.
	 */
	public void setUsername(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>employees.username</code>.
	 */
	public java.lang.String getUsername() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>employees.salt</code>.
	 */
	public void setSalt(java.lang.String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>employees.salt</code>.
	 */
	public java.lang.String getSalt() {
		return (java.lang.String) getValue(10);
	}

	/**
	 * Setter for <code>employees.password</code>.
	 */
	public void setPassword(java.lang.String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>employees.password</code>.
	 */
	public java.lang.String getPassword() {
		return (java.lang.String) getValue(11);
	}

	/**
	 * Setter for <code>employees.note</code>.
	 */
	public void setNote(java.lang.String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>employees.note</code>.
	 */
	public java.lang.String getNote() {
		return (java.lang.String) getValue(12);
	}

	/**
	 * Setter for <code>employees.isBUSDRIVER</code>.
	 */
	public void setIsbusdriver(java.lang.Boolean value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>employees.isBUSDRIVER</code>.
	 */
	public java.lang.Boolean getIsbusdriver() {
		return (java.lang.Boolean) getValue(13);
	}

	/**
	 * Setter for <code>employees.isNETWORK_PLANNER</code>.
	 */
	public void setIsnetworkPlanner(java.lang.Boolean value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>employees.isNETWORK_PLANNER</code>.
	 */
	public java.lang.Boolean getIsnetworkPlanner() {
		return (java.lang.Boolean) getValue(14);
	}

	/**
	 * Setter for <code>employees.isTICKET_PLANNER</code>.
	 */
	public void setIsticketPlanner(java.lang.Boolean value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>employees.isTICKET_PLANNER</code>.
	 */
	public java.lang.Boolean getIsticketPlanner() {
		return (java.lang.Boolean) getValue(15);
	}

	/**
	 * Setter for <code>employees.isHR_MANAGER</code>.
	 */
	public void setIshrManager(java.lang.Boolean value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>employees.isHR_MANAGER</code>.
	 */
	public java.lang.Boolean getIshrManager() {
		return (java.lang.Boolean) getValue(16);
	}

	/**
	 * Setter for <code>employees.isSCHEDULE_MANAGER</code>.
	 */
	public void setIsscheduleManager(java.lang.Boolean value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>employees.isSCHEDULE_MANAGER</code>.
	 */
	public java.lang.Boolean getIsscheduleManager() {
		return (java.lang.Boolean) getValue(17);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record18 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row18<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.Boolean, java.lang.Boolean, java.lang.Boolean, java.lang.Boolean> fieldsRow() {
		return (org.jooq.Row18) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row18<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Boolean, java.lang.Boolean, java.lang.Boolean, java.lang.Boolean, java.lang.Boolean> valuesRow() {
		return (org.jooq.Row18) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES.EMPLOYEES_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES.FIRSTNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES.ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES.ZIPCODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES.CITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES.DATEOFBIRTH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES.PHONE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES.USERNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field11() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES.SALT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field12() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES.PASSWORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field13() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES.NOTE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field14() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES.ISBUSDRIVER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field15() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES.ISNETWORK_PLANNER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field16() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES.ISTICKET_PLANNER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field17() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES.ISHR_MANAGER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field18() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES.ISSCHEDULE_MANAGER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getEmployeesId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getFirstname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getZipcode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getCity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getDateofbirth();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getPhone();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getUsername();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value11() {
		return getSalt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value12() {
		return getPassword();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value13() {
		return getNote();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value14() {
		return getIsbusdriver();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value15() {
		return getIsnetworkPlanner();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value16() {
		return getIsticketPlanner();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value17() {
		return getIshrManager();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value18() {
		return getIsscheduleManager();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmployeesRecord value1(java.lang.Integer value) {
		setEmployeesId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmployeesRecord value2(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmployeesRecord value3(java.lang.String value) {
		setFirstname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmployeesRecord value4(java.lang.String value) {
		setAddress(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmployeesRecord value5(java.lang.String value) {
		setZipcode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmployeesRecord value6(java.lang.String value) {
		setCity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmployeesRecord value7(java.lang.Integer value) {
		setDateofbirth(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmployeesRecord value8(java.lang.String value) {
		setPhone(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmployeesRecord value9(java.lang.String value) {
		setEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmployeesRecord value10(java.lang.String value) {
		setUsername(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmployeesRecord value11(java.lang.String value) {
		setSalt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmployeesRecord value12(java.lang.String value) {
		setPassword(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmployeesRecord value13(java.lang.String value) {
		setNote(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmployeesRecord value14(java.lang.Boolean value) {
		setIsbusdriver(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmployeesRecord value15(java.lang.Boolean value) {
		setIsnetworkPlanner(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmployeesRecord value16(java.lang.Boolean value) {
		setIsticketPlanner(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmployeesRecord value17(java.lang.Boolean value) {
		setIshrManager(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmployeesRecord value18(java.lang.Boolean value) {
		setIsscheduleManager(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmployeesRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, java.lang.Integer value7, java.lang.String value8, java.lang.String value9, java.lang.String value10, java.lang.String value11, java.lang.String value12, java.lang.String value13, java.lang.Boolean value14, java.lang.Boolean value15, java.lang.Boolean value16, java.lang.Boolean value17, java.lang.Boolean value18) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EmployeesRecord
	 */
	public EmployeesRecord() {
		super(de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES);
	}

	/**
	 * Create a detached, initialised EmployeesRecord
	 */
	public EmployeesRecord(java.lang.Integer employeesId, java.lang.String name, java.lang.String firstname, java.lang.String address, java.lang.String zipcode, java.lang.String city, java.lang.Integer dateofbirth, java.lang.String phone, java.lang.String email, java.lang.String username, java.lang.String salt, java.lang.String password, java.lang.String note, java.lang.Boolean isbusdriver, java.lang.Boolean isnetworkPlanner, java.lang.Boolean isticketPlanner, java.lang.Boolean ishrManager, java.lang.Boolean isscheduleManager) {
		super(de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES);

		setValue(0, employeesId);
		setValue(1, name);
		setValue(2, firstname);
		setValue(3, address);
		setValue(4, zipcode);
		setValue(5, city);
		setValue(6, dateofbirth);
		setValue(7, phone);
		setValue(8, email);
		setValue(9, username);
		setValue(10, salt);
		setValue(11, password);
		setValue(12, note);
		setValue(13, isbusdriver);
		setValue(14, isnetworkPlanner);
		setValue(15, isticketPlanner);
		setValue(16, ishrManager);
		setValue(17, isscheduleManager);
	}
}
