/**
 * This class is generated by jOOQ
 */
package de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmployeesRecord extends org.jooq.impl.UpdatableRecordImpl<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.EmployeesRecord> implements org.jooq.Record17<java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Integer, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Boolean, java.lang.Boolean, java.lang.Boolean, java.lang.Boolean, java.lang.Boolean> {

	private static final long serialVersionUID = 812377182;

	/**
	 * Setter for <code>employees.name</code>.
	 */
	public void setName(java.lang.Object value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>employees.name</code>.
	 */
	public java.lang.Object getName() {
		return (java.lang.Object) getValue(0);
	}

	/**
	 * Setter for <code>employees.firstName</code>.
	 */
	public void setFirstname(java.lang.Object value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>employees.firstName</code>.
	 */
	public java.lang.Object getFirstname() {
		return (java.lang.Object) getValue(1);
	}

	/**
	 * Setter for <code>employees.address</code>.
	 */
	public void setAddress(java.lang.Object value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>employees.address</code>.
	 */
	public java.lang.Object getAddress() {
		return (java.lang.Object) getValue(2);
	}

	/**
	 * Setter for <code>employees.zipCode</code>.
	 */
	public void setZipcode(java.lang.Object value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>employees.zipCode</code>.
	 */
	public java.lang.Object getZipcode() {
		return (java.lang.Object) getValue(3);
	}

	/**
	 * Setter for <code>employees.city</code>.
	 */
	public void setCity(java.lang.Object value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>employees.city</code>.
	 */
	public java.lang.Object getCity() {
		return (java.lang.Object) getValue(4);
	}

	/**
	 * Setter for <code>employees.dateOfBirth</code>.
	 */
	public void setDateofbirth(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>employees.dateOfBirth</code>.
	 */
	public java.lang.Integer getDateofbirth() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>employees.phone</code>.
	 */
	public void setPhone(java.lang.Object value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>employees.phone</code>.
	 */
	public java.lang.Object getPhone() {
		return (java.lang.Object) getValue(6);
	}

	/**
	 * Setter for <code>employees.email</code>.
	 */
	public void setEmail(java.lang.Object value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>employees.email</code>.
	 */
	public java.lang.Object getEmail() {
		return (java.lang.Object) getValue(7);
	}

	/**
	 * Setter for <code>employees.username</code>.
	 */
	public void setUsername(java.lang.Object value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>employees.username</code>.
	 */
	public java.lang.Object getUsername() {
		return (java.lang.Object) getValue(8);
	}

	/**
	 * Setter for <code>employees.salt</code>.
	 */
	public void setSalt(java.lang.Object value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>employees.salt</code>.
	 */
	public java.lang.Object getSalt() {
		return (java.lang.Object) getValue(9);
	}

	/**
	 * Setter for <code>employees.password</code>.
	 */
	public void setPassword(java.lang.Object value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>employees.password</code>.
	 */
	public java.lang.Object getPassword() {
		return (java.lang.Object) getValue(10);
	}

	/**
	 * Setter for <code>employees.note</code>.
	 */
	public void setNote(java.lang.Object value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>employees.note</code>.
	 */
	public java.lang.Object getNote() {
		return (java.lang.Object) getValue(11);
	}

	/**
	 * Setter for <code>employees.isBUSDRIVER</code>.
	 */
	public void setIsbusdriver(java.lang.Boolean value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>employees.isBUSDRIVER</code>.
	 */
	public java.lang.Boolean getIsbusdriver() {
		return (java.lang.Boolean) getValue(12);
	}

	/**
	 * Setter for <code>employees.isNETWORK_PLANNER</code>.
	 */
	public void setIsnetworkPlanner(java.lang.Boolean value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>employees.isNETWORK_PLANNER</code>.
	 */
	public java.lang.Boolean getIsnetworkPlanner() {
		return (java.lang.Boolean) getValue(13);
	}

	/**
	 * Setter for <code>employees.isTICKET_PLANNER</code>.
	 */
	public void setIsticketPlanner(java.lang.Boolean value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>employees.isTICKET_PLANNER</code>.
	 */
	public java.lang.Boolean getIsticketPlanner() {
		return (java.lang.Boolean) getValue(14);
	}

	/**
	 * Setter for <code>employees.isHR_MANAGER</code>.
	 */
	public void setIshrManager(java.lang.Boolean value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>employees.isHR_MANAGER</code>.
	 */
	public java.lang.Boolean getIshrManager() {
		return (java.lang.Boolean) getValue(15);
	}

	/**
	 * Setter for <code>employees.isSCHEDULE_MANAGER</code>.
	 */
	public void setIsscheduleManager(java.lang.Boolean value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>employees.isSCHEDULE_MANAGER</code>.
	 */
	public java.lang.Boolean getIsscheduleManager() {
		return (java.lang.Boolean) getValue(16);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Object> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record17 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row17<java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Integer, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Boolean, java.lang.Boolean, java.lang.Boolean, java.lang.Boolean, java.lang.Boolean> fieldsRow() {
		return (org.jooq.Row17) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row17<java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Integer, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Boolean, java.lang.Boolean, java.lang.Boolean, java.lang.Boolean, java.lang.Boolean> valuesRow() {
		return (org.jooq.Row17) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Object> field1() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Object> field2() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES.FIRSTNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Object> field3() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES.ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Object> field4() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES.ZIPCODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Object> field5() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES.CITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES.DATEOFBIRTH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Object> field7() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES.PHONE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Object> field8() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Object> field9() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES.USERNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Object> field10() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES.SALT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Object> field11() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES.PASSWORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Object> field12() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES.NOTE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field13() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES.ISBUSDRIVER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field14() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES.ISNETWORK_PLANNER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field15() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES.ISTICKET_PLANNER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field16() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES.ISHR_MANAGER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field17() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES.ISSCHEDULE_MANAGER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Object value1() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Object value2() {
		return getFirstname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Object value3() {
		return getAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Object value4() {
		return getZipcode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Object value5() {
		return getCity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getDateofbirth();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Object value7() {
		return getPhone();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Object value8() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Object value9() {
		return getUsername();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Object value10() {
		return getSalt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Object value11() {
		return getPassword();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Object value12() {
		return getNote();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value13() {
		return getIsbusdriver();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value14() {
		return getIsnetworkPlanner();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value15() {
		return getIsticketPlanner();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value16() {
		return getIshrManager();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value17() {
		return getIsscheduleManager();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmployeesRecord value1(java.lang.Object value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmployeesRecord value2(java.lang.Object value) {
		setFirstname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmployeesRecord value3(java.lang.Object value) {
		setAddress(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmployeesRecord value4(java.lang.Object value) {
		setZipcode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmployeesRecord value5(java.lang.Object value) {
		setCity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmployeesRecord value6(java.lang.Integer value) {
		setDateofbirth(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmployeesRecord value7(java.lang.Object value) {
		setPhone(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmployeesRecord value8(java.lang.Object value) {
		setEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmployeesRecord value9(java.lang.Object value) {
		setUsername(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmployeesRecord value10(java.lang.Object value) {
		setSalt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmployeesRecord value11(java.lang.Object value) {
		setPassword(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmployeesRecord value12(java.lang.Object value) {
		setNote(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmployeesRecord value13(java.lang.Boolean value) {
		setIsbusdriver(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmployeesRecord value14(java.lang.Boolean value) {
		setIsnetworkPlanner(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmployeesRecord value15(java.lang.Boolean value) {
		setIsticketPlanner(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmployeesRecord value16(java.lang.Boolean value) {
		setIshrManager(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmployeesRecord value17(java.lang.Boolean value) {
		setIsscheduleManager(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EmployeesRecord values(java.lang.Object value1, java.lang.Object value2, java.lang.Object value3, java.lang.Object value4, java.lang.Object value5, java.lang.Integer value6, java.lang.Object value7, java.lang.Object value8, java.lang.Object value9, java.lang.Object value10, java.lang.Object value11, java.lang.Object value12, java.lang.Boolean value13, java.lang.Boolean value14, java.lang.Boolean value15, java.lang.Boolean value16, java.lang.Boolean value17) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EmployeesRecord
	 */
	public EmployeesRecord() {
		super(de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES);
	}

	/**
	 * Create a detached, initialised EmployeesRecord
	 */
	public EmployeesRecord(java.lang.Object name, java.lang.Object firstname, java.lang.Object address, java.lang.Object zipcode, java.lang.Object city, java.lang.Integer dateofbirth, java.lang.Object phone, java.lang.Object email, java.lang.Object username, java.lang.Object salt, java.lang.Object password, java.lang.Object note, java.lang.Boolean isbusdriver, java.lang.Boolean isnetworkPlanner, java.lang.Boolean isticketPlanner, java.lang.Boolean ishrManager, java.lang.Boolean isscheduleManager) {
		super(de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES);

		setValue(0, name);
		setValue(1, firstname);
		setValue(2, address);
		setValue(3, zipcode);
		setValue(4, city);
		setValue(5, dateofbirth);
		setValue(6, phone);
		setValue(7, email);
		setValue(8, username);
		setValue(9, salt);
		setValue(10, password);
		setValue(11, note);
		setValue(12, isbusdriver);
		setValue(13, isnetworkPlanner);
		setValue(14, isticketPlanner);
		setValue(15, ishrManager);
		setValue(16, isscheduleManager);
	}
}
