/**
 * This class is generated by jOOQ
 */
package de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoutesStopsRecord extends org.jooq.impl.UpdatableRecordImpl<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.RoutesStopsRecord> implements org.jooq.Record5<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = 704137914;

	/**
	 * Setter for <code>routes_stops.routes_stops_id</code>.
	 */
	public void setRoutesStopsId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>routes_stops.routes_stops_id</code>.
	 */
	public java.lang.Integer getRoutesStopsId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>routes_stops.routes_id</code>.
	 */
	public void setRoutesId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>routes_stops.routes_id</code>.
	 */
	public java.lang.Integer getRoutesId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>routes_stops.busStops_id</code>.
	 */
	public void setBusstopsId(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>routes_stops.busStops_id</code>.
	 */
	public java.lang.Integer getBusstopsId() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>routes_stops.busStops_stoppingPoints_id</code>.
	 */
	public void setBusstopsStoppingpointsId(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>routes_stops.busStops_stoppingPoints_id</code>.
	 */
	public java.lang.Integer getBusstopsStoppingpointsId() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>routes_stops.timeToPrevious</code>.
	 */
	public void setTimetoprevious(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>routes_stops.timeToPrevious</code>.
	 */
	public java.lang.Integer getTimetoprevious() {
		return (java.lang.Integer) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.RoutesStops.ROUTES_STOPS.ROUTES_STOPS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.RoutesStops.ROUTES_STOPS.ROUTES_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.RoutesStops.ROUTES_STOPS.BUSSTOPS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.RoutesStops.ROUTES_STOPS.BUSSTOPS_STOPPINGPOINTS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.RoutesStops.ROUTES_STOPS.TIMETOPREVIOUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getRoutesStopsId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getRoutesId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getBusstopsId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getBusstopsStoppingpointsId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getTimetoprevious();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RoutesStopsRecord value1(java.lang.Integer value) {
		setRoutesStopsId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RoutesStopsRecord value2(java.lang.Integer value) {
		setRoutesId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RoutesStopsRecord value3(java.lang.Integer value) {
		setBusstopsId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RoutesStopsRecord value4(java.lang.Integer value) {
		setBusstopsStoppingpointsId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RoutesStopsRecord value5(java.lang.Integer value) {
		setTimetoprevious(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RoutesStopsRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Integer value3, java.lang.Integer value4, java.lang.Integer value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RoutesStopsRecord
	 */
	public RoutesStopsRecord() {
		super(de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.RoutesStops.ROUTES_STOPS);
	}

	/**
	 * Create a detached, initialised RoutesStopsRecord
	 */
	public RoutesStopsRecord(java.lang.Integer routesStopsId, java.lang.Integer routesId, java.lang.Integer busstopsId, java.lang.Integer busstopsStoppingpointsId, java.lang.Integer timetoprevious) {
		super(de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.RoutesStops.ROUTES_STOPS);

		setValue(0, routesStopsId);
		setValue(1, routesId);
		setValue(2, busstopsId);
		setValue(3, busstopsStoppingpointsId);
		setValue(4, timetoprevious);
	}
}
