/**
 * This class is generated by jOOQ
 */
package de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoutesStarttimesRecord extends org.jooq.impl.TableRecordImpl<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.RoutesStarttimesRecord> implements org.jooq.Record3<java.lang.Object, java.lang.Object, java.lang.Integer> {

	private static final long serialVersionUID = 1878375595;

	/**
	 * Setter for <code>routes_startTimes.routes_id</code>.
	 */
	public void setRoutesId(java.lang.Object value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>routes_startTimes.routes_id</code>.
	 */
	public java.lang.Object getRoutesId() {
		return (java.lang.Object) getValue(0);
	}

	/**
	 * Setter for <code>routes_startTimes.dayOfWeek</code>.
	 */
	public void setDayofweek(java.lang.Object value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>routes_startTimes.dayOfWeek</code>.
	 */
	public java.lang.Object getDayofweek() {
		return (java.lang.Object) getValue(1);
	}

	/**
	 * Setter for <code>routes_startTimes.startTime</code>.
	 */
	public void setStarttime(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>routes_startTimes.startTime</code>.
	 */
	public java.lang.Integer getStarttime() {
		return (java.lang.Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Object, java.lang.Object, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Object, java.lang.Object, java.lang.Integer> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Object> field1() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.RoutesStarttimes.ROUTES_STARTTIMES.ROUTES_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Object> field2() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.RoutesStarttimes.ROUTES_STARTTIMES.DAYOFWEEK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.RoutesStarttimes.ROUTES_STARTTIMES.STARTTIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Object value1() {
		return getRoutesId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Object value2() {
		return getDayofweek();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getStarttime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RoutesStarttimesRecord value1(java.lang.Object value) {
		setRoutesId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RoutesStarttimesRecord value2(java.lang.Object value) {
		setDayofweek(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RoutesStarttimesRecord value3(java.lang.Integer value) {
		setStarttime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RoutesStarttimesRecord values(java.lang.Object value1, java.lang.Object value2, java.lang.Integer value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RoutesStarttimesRecord
	 */
	public RoutesStarttimesRecord() {
		super(de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.RoutesStarttimes.ROUTES_STARTTIMES);
	}

	/**
	 * Create a detached, initialised RoutesStarttimesRecord
	 */
	public RoutesStarttimesRecord(java.lang.Object routesId, java.lang.Object dayofweek, java.lang.Integer starttime) {
		super(de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.RoutesStarttimes.ROUTES_STARTTIMES);

		setValue(0, routesId);
		setValue(1, dayofweek);
		setValue(2, starttime);
	}
}
