/**
 * This class is generated by jOOQ
 */
package de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoutesStopsRecord extends org.jooq.impl.TableRecordImpl<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.RoutesStopsRecord> implements org.jooq.Record5<java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Integer> {

	private static final long serialVersionUID = 1509743343;

	/**
	 * Setter for <code>routes_stops.routes_id</code>.
	 */
	public void setRoutesId(java.lang.Object value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>routes_stops.routes_id</code>.
	 */
	public java.lang.Object getRoutesId() {
		return (java.lang.Object) getValue(0);
	}

	/**
	 * Setter for <code>routes_stops.busStops_name</code>.
	 */
	public void setBusstopsName(java.lang.Object value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>routes_stops.busStops_name</code>.
	 */
	public java.lang.Object getBusstopsName() {
		return (java.lang.Object) getValue(1);
	}

	/**
	 * Setter for <code>routes_stops.busStops_locationX</code>.
	 */
	public void setBusstopsLocationx(java.lang.Object value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>routes_stops.busStops_locationX</code>.
	 */
	public java.lang.Object getBusstopsLocationx() {
		return (java.lang.Object) getValue(2);
	}

	/**
	 * Setter for <code>routes_stops.busStops_locationY</code>.
	 */
	public void setBusstopsLocationy(java.lang.Object value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>routes_stops.busStops_locationY</code>.
	 */
	public java.lang.Object getBusstopsLocationy() {
		return (java.lang.Object) getValue(3);
	}

	/**
	 * Setter for <code>routes_stops.timeToPrevious</code>.
	 */
	public void setTimetoprevious(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>routes_stops.timeToPrevious</code>.
	 */
	public java.lang.Integer getTimetoprevious() {
		return (java.lang.Integer) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Object, java.lang.Integer> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Object> field1() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.RoutesStops.ROUTES_STOPS.ROUTES_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Object> field2() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.RoutesStops.ROUTES_STOPS.BUSSTOPS_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Object> field3() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.RoutesStops.ROUTES_STOPS.BUSSTOPS_LOCATIONX;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Object> field4() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.RoutesStops.ROUTES_STOPS.BUSSTOPS_LOCATIONY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.RoutesStops.ROUTES_STOPS.TIMETOPREVIOUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Object value1() {
		return getRoutesId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Object value2() {
		return getBusstopsName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Object value3() {
		return getBusstopsLocationx();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Object value4() {
		return getBusstopsLocationy();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getTimetoprevious();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RoutesStopsRecord value1(java.lang.Object value) {
		setRoutesId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RoutesStopsRecord value2(java.lang.Object value) {
		setBusstopsName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RoutesStopsRecord value3(java.lang.Object value) {
		setBusstopsLocationx(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RoutesStopsRecord value4(java.lang.Object value) {
		setBusstopsLocationy(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RoutesStopsRecord value5(java.lang.Integer value) {
		setTimetoprevious(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RoutesStopsRecord values(java.lang.Object value1, java.lang.Object value2, java.lang.Object value3, java.lang.Object value4, java.lang.Integer value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RoutesStopsRecord
	 */
	public RoutesStopsRecord() {
		super(de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.RoutesStops.ROUTES_STOPS);
	}

	/**
	 * Create a detached, initialised RoutesStopsRecord
	 */
	public RoutesStopsRecord(java.lang.Object routesId, java.lang.Object busstopsName, java.lang.Object busstopsLocationx, java.lang.Object busstopsLocationy, java.lang.Integer timetoprevious) {
		super(de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.RoutesStops.ROUTES_STOPS);

		setValue(0, routesId);
		setValue(1, busstopsName);
		setValue(2, busstopsLocationx);
		setValue(3, busstopsLocationy);
		setValue(4, timetoprevious);
	}
}
