/**
 * This class is generated by jOOQ
 */
package de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SoldticketsRecord extends org.jooq.impl.UpdatableRecordImpl<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.SoldticketsRecord> implements org.jooq.Record4<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = -1596214172;

	/**
	 * Setter for <code>soldTickets.soldTickets_id</code>.
	 */
	public void setSoldticketsId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>soldTickets.soldTickets_id</code>.
	 */
	public java.lang.Integer getSoldticketsId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>soldTickets.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>soldTickets.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>soldTickets.timestamp</code>.
	 */
	public void setTimestamp(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>soldTickets.timestamp</code>.
	 */
	public java.lang.Integer getTimestamp() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>soldTickets.price</code>.
	 */
	public void setPrice(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>soldTickets.price</code>.
	 */
	public java.lang.Integer getPrice() {
		return (java.lang.Integer) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Soldtickets.SOLDTICKETS.SOLDTICKETS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Soldtickets.SOLDTICKETS.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Soldtickets.SOLDTICKETS.TIMESTAMP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Soldtickets.SOLDTICKETS.PRICE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getSoldticketsId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getTimestamp();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getPrice();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SoldticketsRecord value1(java.lang.Integer value) {
		setSoldticketsId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SoldticketsRecord value2(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SoldticketsRecord value3(java.lang.Integer value) {
		setTimestamp(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SoldticketsRecord value4(java.lang.Integer value) {
		setPrice(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SoldticketsRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.Integer value3, java.lang.Integer value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SoldticketsRecord
	 */
	public SoldticketsRecord() {
		super(de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Soldtickets.SOLDTICKETS);
	}

	/**
	 * Create a detached, initialised SoldticketsRecord
	 */
	public SoldticketsRecord(java.lang.Integer soldticketsId, java.lang.String name, java.lang.Integer timestamp, java.lang.Integer price) {
		super(de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Soldtickets.SOLDTICKETS);

		setValue(0, soldticketsId);
		setValue(1, name);
		setValue(2, timestamp);
		setValue(3, price);
	}
}
