/**
 * This class is generated by jOOQ
 */
package de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TesttabelleRecord extends org.jooq.impl.TableRecordImpl<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.TesttabelleRecord> implements org.jooq.Record4<java.lang.String, java.lang.String, java.lang.String, java.lang.Object> {

	private static final long serialVersionUID = -1804481527;

	/**
	 * Setter for <code>testtabelle.spalte1</code>.
	 */
	public void setSpalte1(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>testtabelle.spalte1</code>.
	 */
	public java.lang.String getSpalte1() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>testtabelle.spalte2</code>.
	 */
	public void setSpalte2(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>testtabelle.spalte2</code>.
	 */
	public java.lang.String getSpalte2() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>testtabelle.spalte3</code>.
	 */
	public void setSpalte3(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>testtabelle.spalte3</code>.
	 */
	public java.lang.String getSpalte3() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>testtabelle.spalte4</code>.
	 */
	public void setSpalte4(java.lang.Object value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>testtabelle.spalte4</code>.
	 */
	public java.lang.Object getSpalte4() {
		return (java.lang.Object) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.String, java.lang.String, java.lang.String, java.lang.Object> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.String, java.lang.String, java.lang.String, java.lang.Object> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Testtabelle.TESTTABELLE.SPALTE1;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Testtabelle.TESTTABELLE.SPALTE2;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Testtabelle.TESTTABELLE.SPALTE3;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Object> field4() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Testtabelle.TESTTABELLE.SPALTE4;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getSpalte1();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getSpalte2();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getSpalte3();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Object value4() {
		return getSpalte4();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TesttabelleRecord value1(java.lang.String value) {
		setSpalte1(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TesttabelleRecord value2(java.lang.String value) {
		setSpalte2(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TesttabelleRecord value3(java.lang.String value) {
		setSpalte3(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TesttabelleRecord value4(java.lang.Object value) {
		setSpalte4(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TesttabelleRecord values(java.lang.String value1, java.lang.String value2, java.lang.String value3, java.lang.Object value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TesttabelleRecord
	 */
	public TesttabelleRecord() {
		super(de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Testtabelle.TESTTABELLE);
	}

	/**
	 * Create a detached, initialised TesttabelleRecord
	 */
	public TesttabelleRecord(java.lang.String spalte1, java.lang.String spalte2, java.lang.String spalte3, java.lang.Object spalte4) {
		super(de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Testtabelle.TESTTABELLE);

		setValue(0, spalte1);
		setValue(1, spalte2);
		setValue(2, spalte3);
		setValue(3, spalte4);
	}
}
