/**
 * This class is generated by jOOQ
 */
package de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TicketsRecord extends org.jooq.impl.TableRecordImpl<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.TicketsRecord> implements org.jooq.Record4<java.lang.Object, java.lang.Integer, java.lang.Integer, java.lang.Object> {

	private static final long serialVersionUID = -1223739224;

	/**
	 * Setter for <code>tickets.name</code>.
	 */
	public void setName(java.lang.Object value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>tickets.name</code>.
	 */
	public java.lang.Object getName() {
		return (java.lang.Object) getValue(0);
	}

	/**
	 * Setter for <code>tickets.price</code>.
	 */
	public void setPrice(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>tickets.price</code>.
	 */
	public java.lang.Integer getPrice() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>tickets.numPassengers</code>.
	 */
	public void setNumpassengers(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>tickets.numPassengers</code>.
	 */
	public java.lang.Integer getNumpassengers() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>tickets.descritption</code>.
	 */
	public void setDescritption(java.lang.Object value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>tickets.descritption</code>.
	 */
	public java.lang.Object getDescritption() {
		return (java.lang.Object) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Object, java.lang.Integer, java.lang.Integer, java.lang.Object> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Object, java.lang.Integer, java.lang.Integer, java.lang.Object> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Object> field1() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Tickets.TICKETS.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Tickets.TICKETS.PRICE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Tickets.TICKETS.NUMPASSENGERS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Object> field4() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Tickets.TICKETS.DESCRITPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Object value1() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getPrice();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getNumpassengers();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Object value4() {
		return getDescritption();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TicketsRecord value1(java.lang.Object value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TicketsRecord value2(java.lang.Integer value) {
		setPrice(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TicketsRecord value3(java.lang.Integer value) {
		setNumpassengers(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TicketsRecord value4(java.lang.Object value) {
		setDescritption(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TicketsRecord values(java.lang.Object value1, java.lang.Integer value2, java.lang.Integer value3, java.lang.Object value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TicketsRecord
	 */
	public TicketsRecord() {
		super(de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Tickets.TICKETS);
	}

	/**
	 * Create a detached, initialised TicketsRecord
	 */
	public TicketsRecord(java.lang.Object name, java.lang.Integer price, java.lang.Integer numpassengers, java.lang.Object descritption) {
		super(de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Tickets.TICKETS);

		setValue(0, name);
		setValue(1, price);
		setValue(2, numpassengers);
		setValue(3, descritption);
	}
}
