/**
 * This class is generated by jOOQ
 */
package de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ToursRecord extends org.jooq.impl.TableRecordImpl<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.ToursRecord> implements org.jooq.Record4<java.lang.Integer, java.lang.Object, java.lang.Object, java.lang.Object> {

	private static final long serialVersionUID = 813653699;

	/**
	 * Setter for <code>tours.date</code>.
	 */
	public void setDate(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>tours.date</code>.
	 */
	public java.lang.Integer getDate() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>tours.routes_id</code>.
	 */
	public void setRoutesId(java.lang.Object value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>tours.routes_id</code>.
	 */
	public java.lang.Object getRoutesId() {
		return (java.lang.Object) getValue(1);
	}

	/**
	 * Setter for <code>tours.bus_licensePlate</code>.
	 */
	public void setBusLicenseplate(java.lang.Object value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>tours.bus_licensePlate</code>.
	 */
	public java.lang.Object getBusLicenseplate() {
		return (java.lang.Object) getValue(2);
	}

	/**
	 * Setter for <code>tours.employee_username</code>.
	 */
	public void setEmployeeUsername(java.lang.Object value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>tours.employee_username</code>.
	 */
	public java.lang.Object getEmployeeUsername() {
		return (java.lang.Object) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.Object, java.lang.Object, java.lang.Object> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.Object, java.lang.Object, java.lang.Object> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Tours.TOURS.DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Object> field2() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Tours.TOURS.ROUTES_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Object> field3() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Tours.TOURS.BUS_LICENSEPLATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Object> field4() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Tours.TOURS.EMPLOYEE_USERNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Object value2() {
		return getRoutesId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Object value3() {
		return getBusLicenseplate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Object value4() {
		return getEmployeeUsername();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ToursRecord value1(java.lang.Integer value) {
		setDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ToursRecord value2(java.lang.Object value) {
		setRoutesId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ToursRecord value3(java.lang.Object value) {
		setBusLicenseplate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ToursRecord value4(java.lang.Object value) {
		setEmployeeUsername(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ToursRecord values(java.lang.Integer value1, java.lang.Object value2, java.lang.Object value3, java.lang.Object value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ToursRecord
	 */
	public ToursRecord() {
		super(de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Tours.TOURS);
	}

	/**
	 * Create a detached, initialised ToursRecord
	 */
	public ToursRecord(java.lang.Integer date, java.lang.Object routesId, java.lang.Object busLicenseplate, java.lang.Object employeeUsername) {
		super(de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Tours.TOURS);

		setValue(0, date);
		setValue(1, routesId);
		setValue(2, busLicenseplate);
		setValue(3, employeeUsername);
	}
}
