package de.uni_muenster.sopra2015.gruppe8.octobus.view.listeners;

/**
 * Created by Lars on 03-Mar-15.
 */
public enum EmitterButton
{
	PANEL_PASSENGER_SHOW_NETWORK,
	PANEL_PASSENGER_SEARCH_CONNECTION,
	PANEL_PASSENGER_SHOW_TICKETS,
	PANEL_PASSENGER_LOGIN,
	PANEL_EMPLOYEE_LOGOUT,
	PANEL_EMPLOYEE_CHANGE_PASSWORD,
	FORM_LOGIN_LOGIN,
	FORM_LOGIN_CANCEL,
	FORM_CHANGE_PASSWORD_SAVE,
	FORM_CHANGE_PASSWORD_CANCEL,
	FORM_BUS_SAVE,
	FORM_BUS_CANCEL
}
