/**
 * This class is generated by jOOQ
 */
package de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Employees extends org.jooq.impl.TableImpl<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.EmployeesRecord> {

	private static final long serialVersionUID = 1881079955;

	/**
	 * The reference instance of <code>employees</code>
	 */
	public static final de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees EMPLOYEES = new de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.EmployeesRecord> getRecordType() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.EmployeesRecord.class;
	}

	/**
	 * The column <code>employees.employees_id</code>.
	 */
	public final org.jooq.TableField<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.EmployeesRecord, java.lang.Integer> EMPLOYEES_ID = createField("employees_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>employees.name</code>.
	 */
	public final org.jooq.TableField<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.EmployeesRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB.length(200), this, "");

	/**
	 * The column <code>employees.firstName</code>.
	 */
	public final org.jooq.TableField<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.EmployeesRecord, java.lang.String> FIRSTNAME = createField("firstName", org.jooq.impl.SQLDataType.CLOB.length(200), this, "");

	/**
	 * The column <code>employees.address</code>.
	 */
	public final org.jooq.TableField<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.EmployeesRecord, java.lang.String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.CLOB.length(200), this, "");

	/**
	 * The column <code>employees.zipCode</code>.
	 */
	public final org.jooq.TableField<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.EmployeesRecord, java.lang.String> ZIPCODE = createField("zipCode", org.jooq.impl.SQLDataType.CLOB.length(10), this, "");

	/**
	 * The column <code>employees.city</code>.
	 */
	public final org.jooq.TableField<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.EmployeesRecord, java.lang.String> CITY = createField("city", org.jooq.impl.SQLDataType.CLOB.length(200), this, "");

	/**
	 * The column <code>employees.dateOfBirth</code>.
	 */
	public final org.jooq.TableField<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.EmployeesRecord, java.lang.Integer> DATEOFBIRTH = createField("dateOfBirth", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>employees.phone</code>.
	 */
	public final org.jooq.TableField<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.EmployeesRecord, java.lang.String> PHONE = createField("phone", org.jooq.impl.SQLDataType.CLOB.length(200), this, "");

	/**
	 * The column <code>employees.email</code>.
	 */
	public final org.jooq.TableField<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.EmployeesRecord, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.CLOB.length(200), this, "");

	/**
	 * The column <code>employees.username</code>.
	 */
	public final org.jooq.TableField<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.EmployeesRecord, java.lang.String> USERNAME = createField("username", org.jooq.impl.SQLDataType.CLOB.length(10).nullable(false), this, "");

	/**
	 * The column <code>employees.salt</code>.
	 */
	public final org.jooq.TableField<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.EmployeesRecord, java.lang.String> SALT = createField("salt", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>employees.password</code>.
	 */
	public final org.jooq.TableField<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.EmployeesRecord, java.lang.String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>employees.note</code>.
	 */
	public final org.jooq.TableField<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.EmployeesRecord, java.lang.String> NOTE = createField("note", org.jooq.impl.SQLDataType.CLOB.length(2000), this, "");

	/**
	 * The column <code>employees.isBUSDRIVER</code>.
	 */
	public final org.jooq.TableField<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.EmployeesRecord, java.lang.Boolean> ISBUSDRIVER = createField("isBUSDRIVER", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * The column <code>employees.isNETWORK_PLANNER</code>.
	 */
	public final org.jooq.TableField<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.EmployeesRecord, java.lang.Boolean> ISNETWORK_PLANNER = createField("isNETWORK_PLANNER", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * The column <code>employees.isTICKET_PLANNER</code>.
	 */
	public final org.jooq.TableField<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.EmployeesRecord, java.lang.Boolean> ISTICKET_PLANNER = createField("isTICKET_PLANNER", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * The column <code>employees.isHR_MANAGER</code>.
	 */
	public final org.jooq.TableField<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.EmployeesRecord, java.lang.Boolean> ISHR_MANAGER = createField("isHR_MANAGER", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * The column <code>employees.isSCHEDULE_MANAGER</code>.
	 */
	public final org.jooq.TableField<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.EmployeesRecord, java.lang.Boolean> ISSCHEDULE_MANAGER = createField("isSCHEDULE_MANAGER", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * Create a <code>employees</code> table reference
	 */
	public Employees() {
		this("employees", null);
	}

	/**
	 * Create an aliased <code>employees</code> table reference
	 */
	public Employees(java.lang.String alias) {
		this(alias, de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees.EMPLOYEES);
	}

	private Employees(java.lang.String alias, org.jooq.Table<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.EmployeesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Employees(java.lang.String alias, org.jooq.Table<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.EmployeesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.EmployeesRecord, java.lang.Integer> getIdentity() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.Keys.IDENTITY_EMPLOYEES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.EmployeesRecord> getPrimaryKey() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.Keys.PK_EMPLOYEES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.EmployeesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.EmployeesRecord>>asList(de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.Keys.PK_EMPLOYEES);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees as(java.lang.String alias) {
		return new de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees(alias, this);
	}

	/**
	 * Rename this table
	 */
	public de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees rename(java.lang.String name) {
		return new de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Employees(name, null);
	}
}
