/**
 * This class is generated by jOOQ
 */
package de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoutesStops extends org.jooq.impl.TableImpl<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.RoutesStopsRecord> {

	private static final long serialVersionUID = -1430420681;

	/**
	 * The reference instance of <code>routes_stops</code>
	 */
	public static final de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.RoutesStops ROUTES_STOPS = new de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.RoutesStops();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.RoutesStopsRecord> getRecordType() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.RoutesStopsRecord.class;
	}

	/**
	 * The column <code>routes_stops.routes_id</code>.
	 */
	public final org.jooq.TableField<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.RoutesStopsRecord, java.lang.Object> ROUTES_ID = createField("routes_id", org.jooq.impl.DefaultDataType.getDefaultDataType(""), this, "");

	/**
	 * The column <code>routes_stops.busStops_name</code>.
	 */
	public final org.jooq.TableField<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.RoutesStopsRecord, java.lang.Object> BUSSTOPS_NAME = createField("busStops_name", org.jooq.impl.DefaultDataType.getDefaultDataType(""), this, "");

	/**
	 * The column <code>routes_stops.busStops_locationX</code>.
	 */
	public final org.jooq.TableField<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.RoutesStopsRecord, java.lang.Object> BUSSTOPS_LOCATIONX = createField("busStops_locationX", org.jooq.impl.DefaultDataType.getDefaultDataType(""), this, "");

	/**
	 * The column <code>routes_stops.busStops_locationY</code>.
	 */
	public final org.jooq.TableField<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.RoutesStopsRecord, java.lang.Object> BUSSTOPS_LOCATIONY = createField("busStops_locationY", org.jooq.impl.DefaultDataType.getDefaultDataType(""), this, "");

	/**
	 * The column <code>routes_stops.timeToPrevious</code>.
	 */
	public final org.jooq.TableField<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.RoutesStopsRecord, java.lang.Integer> TIMETOPREVIOUS = createField("timeToPrevious", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>routes_stops</code> table reference
	 */
	public RoutesStops() {
		this("routes_stops", null);
	}

	/**
	 * Create an aliased <code>routes_stops</code> table reference
	 */
	public RoutesStops(java.lang.String alias) {
		this(alias, de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.RoutesStops.ROUTES_STOPS);
	}

	private RoutesStops(java.lang.String alias, org.jooq.Table<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.RoutesStopsRecord> aliased) {
		this(alias, aliased, null);
	}

	private RoutesStops(java.lang.String alias, org.jooq.Table<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.RoutesStopsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.RoutesStopsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.RoutesStopsRecord, ?>>asList(de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.Keys.FK_ROUTES_STOPS_ROUTES_1, de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.Keys.FK_ROUTES_STOPS_BUSSTOPS_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.RoutesStops as(java.lang.String alias) {
		return new de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.RoutesStops(alias, this);
	}

	/**
	 * Rename this table
	 */
	public de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.RoutesStops rename(java.lang.String name) {
		return new de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.RoutesStops(name, null);
	}
}
