/**
 * This class is generated by jOOQ
 */
package de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Soldtickets extends org.jooq.impl.TableImpl<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.SoldticketsRecord> {

	private static final long serialVersionUID = -299977944;

	/**
	 * The reference instance of <code>soldTickets</code>
	 */
	public static final de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Soldtickets SOLDTICKETS = new de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Soldtickets();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.SoldticketsRecord> getRecordType() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.SoldticketsRecord.class;
	}

	/**
	 * The column <code>soldTickets.name</code>.
	 */
	public final org.jooq.TableField<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.SoldticketsRecord, java.lang.Object> NAME = createField("name", org.jooq.impl.DefaultDataType.getDefaultDataType("STRING "), this, "");

	/**
	 * The column <code>soldTickets.date</code>.
	 */
	public final org.jooq.TableField<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.SoldticketsRecord, java.lang.Integer> DATE = createField("date", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>soldTickets.price</code>.
	 */
	public final org.jooq.TableField<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.SoldticketsRecord, java.lang.Integer> PRICE = createField("price", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>soldTickets</code> table reference
	 */
	public Soldtickets() {
		this("soldTickets", null);
	}

	/**
	 * Create an aliased <code>soldTickets</code> table reference
	 */
	public Soldtickets(java.lang.String alias) {
		this(alias, de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Soldtickets.SOLDTICKETS);
	}

	private Soldtickets(java.lang.String alias, org.jooq.Table<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.SoldticketsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Soldtickets(java.lang.String alias, org.jooq.Table<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.SoldticketsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Soldtickets as(java.lang.String alias) {
		return new de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Soldtickets(alias, this);
	}

	/**
	 * Rename this table
	 */
	public de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Soldtickets rename(java.lang.String name) {
		return new de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Soldtickets(name, null);
	}
}
