/**
 * This class is generated by jOOQ
 */
package de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.3"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Testtabelle extends org.jooq.impl.TableImpl<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.TesttabelleRecord> {

	private static final long serialVersionUID = -1159208848;

	/**
	 * The reference instance of <code>testtabelle</code>
	 */
	public static final de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Testtabelle TESTTABELLE = new de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Testtabelle();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.TesttabelleRecord> getRecordType() {
		return de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.TesttabelleRecord.class;
	}

	/**
	 * The column <code>testtabelle.spalte1</code>.
	 */
	public final org.jooq.TableField<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.TesttabelleRecord, java.lang.String> SPALTE1 = createField("spalte1", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>testtabelle.spalte2</code>.
	 */
	public final org.jooq.TableField<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.TesttabelleRecord, java.lang.String> SPALTE2 = createField("spalte2", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>testtabelle.spalte3</code>.
	 */
	public final org.jooq.TableField<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.TesttabelleRecord, java.lang.String> SPALTE3 = createField("spalte3", org.jooq.impl.SQLDataType.CHAR, this, "");

	/**
	 * The column <code>testtabelle.spalte4</code>.
	 */
	public final org.jooq.TableField<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.TesttabelleRecord, java.lang.Object> SPALTE4 = createField("spalte4", org.jooq.impl.DefaultDataType.getDefaultDataType("STRING"), this, "");

	/**
	 * Create a <code>testtabelle</code> table reference
	 */
	public Testtabelle() {
		this("testtabelle", null);
	}

	/**
	 * Create an aliased <code>testtabelle</code> table reference
	 */
	public Testtabelle(java.lang.String alias) {
		this(alias, de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Testtabelle.TESTTABELLE);
	}

	private Testtabelle(java.lang.String alias, org.jooq.Table<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.TesttabelleRecord> aliased) {
		this(alias, aliased, null);
	}

	private Testtabelle(java.lang.String alias, org.jooq.Table<de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.records.TesttabelleRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Testtabelle as(java.lang.String alias) {
		return new de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Testtabelle(alias, this);
	}

	/**
	 * Rename this table
	 */
	public de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Testtabelle rename(java.lang.String name) {
		return new de.uni_muenster.sopra2015.gruppe8.octobus.jooqGenerated.tables.Testtabelle(name, null);
	}
}
