package de.uni_muenster.sopra2015.gruppe8.octobus.controller.listeners;

/**
 * Used to describe buttons.
 * Each button has a unique value consisting of the source class and its name
 */
public enum EmitterButton
{
	PANEL_PASSENGER_SHOW_NETWORK,
	PANEL_PASSENGER_SEARCH_CONNECTION,
	PANEL_PASSENGER_SHOW_TICKETS,
	PANEL_PASSENGER_LOGIN,

	PANEL_EMPLOYEE_LOGOUT,
	PANEL_EMPLOYEE_CHANGE_PASSWORD,

	FORM_LOGIN_LOGIN,
	FORM_LOGIN_CANCEL,

	FORM_CHANGE_PASSWORD_SAVE,
	FORM_CHANGE_PASSWORD_CANCEL,

	FORM_BUS_SAVE,
	FORM_BUS_CANCEL,

	FORM_BUS_STOP_SAVE,
	FORM_BUS_STOP_CANCEL,

	FORM_EMPLOYEE_SAVE,
	FORM_EMPLOYEE_CANCEL,

	FORM_TICKET_SAVE,
	FORM_TICKET_CANCEL,

	TAB_BUS_NEW,
	TAB_BUS_EDIT,
	TAB_BUS_DELETE,

	TAB_EMPLOYEE_NEW,
	TAB_EMPLOYEE_EDIT,
	TAB_EMPLOYEE_DELETE,

	TAB_TICKET_NEW,
	TAB_TICKET_EDIT,
	TAB_TICKET_DELETE,

	TAB_BUS_STOP_NEW,
	TAB_BUS_STOP_EDIT,
	TAB_BUS_STOP_DELETE
}
