package de.uni_muenster.sopra2015.gruppe8.octobus.controller.listeners;

/**
 * Used to adress tables.
 * Each value represents a unique table.
 */
public enum EmitterTable {
    FORM_JOURNEY_SEARCH_RESULT,
	FORM_ROUTE_STEP1_CURRENT,
	FORM_ROUTE_STEP1_AVAILABLE,
	FORM_ROUTE_STEP2_MONDAY,
	FORM_ROUTE_STEP2_TUESDAY,
	FORM_ROUTE_STEP2_WEDNESDAY,
	FORM_ROUTE_STEP2_THURSDAY,
	FORM_ROUTE_STEP2_FRIDAY,
	FORM_ROUTE_STEP2_SATURDAY,
	FORM_ROUTE_STEP2_SUNDAY,
	TAB_BUS,
	TAB_TICKET,
	TAB_BUSSTOP,
	TAB_EMPLOYEE,
	TAB_ROUTE,
	TAB_SCHEDULE,
	TAB_NETWORK,
	TAB_WORKPLAN
}
